export type QueryResult = Promise<{
    status: number;
    result: string;
}>;

export type SortOptions = "newest"
    | "oldest"
    | "popularity"
    | "positive-feedback"
    | "most-completed"
    | "least-completed"
    | "hardest"
    | "easiest"
    | "name"
    | "relevance"
    | "low-satisfaction";

export type LanguageOptions = "all"
    | "my-languages"
    | "agda"
    | "bf"
    | "c"
    | "cfml"
    | "clojure"
    | "cobol"
    | "coffeescript"
    | "commonlisp"
    | "coq"
    | "c++"
    | "crystal"
    | "c#"
    | "d"
    | "dart"
    | "elixir"
    | "elm"
    | "erlang"
    | "factor"
    | "forth"
    | "fortran"
    | "f#"
    | "go"
    | "groovy"
    | "haskell"
    | "haxe"
    | "idris"
    | "java"
    | "javascript"
    | "julia"
    | "kotlin"
    | "λ calculus"
    | "lean"
    | "lua"
    | "nasm"
    | "nim"
    | "objective-c"
    | "ocaml"
    | "pascal"
    | "perl"
    | "php"
    | "powershell"
    | "prolog"
    | "purescript"
    | "python"
    | "r"
    | "racket"
    | "raku"
    | "reason"
    | "risc-v"
    | "ruby"
    | "rust"
    | "scala"
    | "shell"
    | "solidity"
    | "sql"
    | "swift"
    | "typescript"
    | "vb";

export type StatusOptions = "approved-and-beta"
    | "approved"
    | "beta";

export type ProgressOptions = "all"
    | "kata-untrained"
    | "kata-incomplete"
    | "kata-completed";

export type DifficultyOptions = 8 | 7 | 6 | 5 | 4 | 3 | 2 | 1;

export type TagOptions = "ASCII Art"
    | "Algebra"
    | "Algorithms"
    | "Angular"
    | "Arrays"
    | "Artificial Intelligence"
    | "Asynchronous"
    | "Backend"
    | "Big Integers"
    | "Binary"
    | "Binary Search Trees"
    | "Binary Trees"
    | "Bits"
    | "Cellular Automata"
    | "Ciphers"
    | "Combinatorics"
    | "Compilers"
    | "Cryptography"
    | "Data Science"
    | "Data Structures"
    | "Databases"
    | "Date Time"
    | "Debugging"
    | "Decorator"
    | "Design Patterns"
    | "Discrete Mathematics"
    | "Domain Specific Languages"
    | "Dynamic Programming"
    | "Esoteric Languages"
    | "Event Handling"
    | "Express"
    | "Filtering"
    | "Functional Programming"
    | "Fundamentals"
    | "Game Solvers"
    | "Games"
    | "Genetic Algorithms"
    | "Geometry"
    | "Graph Theory"
    | "Graphics"
    | "Graphs"
    | "Heaps"
    | "Image Processing"
    | "Interpreters"
    | "Iterators"
    | "JSON"
    | "Language Features"
    | "Linear Algebra"
    | "Linked Lists"
    | "Lists"
    | "Logic"
    | "Machine Learning"
    | "Mathematics"
    | "Matrix"
    | "Memoization"
    | "Metaprogramming"
    | "Monads"
    | "MongoDB"
    | "Networks"
    | "Neural Networks"
    | "Number Theory"
    | "Object-oriented Programming"
    | "Parsing"
    | "Performance"
    | "Permutations"
    | "Physics"
    | "Probability"
    | "Promises"
    | "Puzzles"
    | "Queues"
    | "React"
    | "Reactive Programming"
    | "Recursion"
    | "Refactoring"
    | "Reflection"
    | "Regular Expressions"
    | "Restricted"
    | "Reverse Engineering"
    | "Riddles"
    | "RxJS"
    | "SQL"
    | "Scheduling"
    | "Searching"
    | "Security"
    | "Set Theory"
    | "Sets"
    | "Simulation"
    | "Singleton"
    | "Sorting"
    | "Stacks"
    | "State Machines"
    | "Statistics"
    | "Streams"
    | "Strings"
    | "Trees"
    | "Tutorials"
    | "Unicode"
    | "Web Scraping"
    | "Web3"

export interface QueryOptions {
    sortBy: SortOptions;
    language: LanguageOptions;
    status: StatusOptions;
    progress: ProgressOptions;
    difficulty: DifficultyOptions[];
    tags: TagOptions[];
}
